### ISSUE TITLE
IllegalSelectionIndexException: Illegal selection index for text with length 133, selectionStart: 247, selectionEnd: 247, with Un...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/gutenberg-mobile#2348]
@mchowning It looks like you might have added this exception, so this error might be an interest for you.

**Sentry Url**: https://sentry.io/share/issue/e3a52a1ab72c48b8aa6e7d91802341d9/
**User Count**: 209
**Count**: 681
**First Release**: org.wordpress.android-14.8-rc-1
**First Seen**: 2020-05-20T12:26:49Z
**Last Seen**: 2020-06-04T16:25:56Z
**24 Hours**: 310
**30 Days**: 585

```
IllegalSelectionIndexException: Illegal selection index for text with length 133, selectionStart: 247, selectionEnd: 247, with UnknownHtmlSpan tags: []
     at org.wordpress.mobile.ReactNativeAztec.ReactAztecManager.updateSelectionIfNeeded(ReactAztecManager.java:242)
     at org.wordpress.mobile.ReactNativeAztec.ReactAztecManager.setTextfromJS(ReactAztecManager.java:224)
     at org.wordpress.mobile.ReactNativeAztec.ReactAztecManager.setText(ReactAztecManager.java:206)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
     at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
     at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
     at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:87)
...
(18 additional frame(s) were not displayed)
```

**Comment by mchowning** [comment]
A lot of context behind the crash that was happening before we caught the IllegalIndexException and instead started sending this non-crashing custom `IllegalSelectionIndexException` to Sentry is available in the issue for the old crash: https://github.com/wordpress-mobile/WordPress-Android/issues/9832
