### ISSUE TITLE
Failure building the iOS demo app from the command line

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#2651]
The build fails when trying to build the iOS demo app from the command line.

Steps to reproduce:
1. Do a typical `npm ci` in the gb-mobile root to install the NPM packages from scratch
2. In a second terminal window, run `npm run start:reset` to launch Metro
3. In the first terminal window, do `npm run core ios` to build and launch the iOS demo app in a simulator
4. The build will generally go a long way, the simulator will open but, in the stage where the app would be installed the following error occurs:

```
info Found Xcode workspace "gutenberg.xcworkspace"
info Building (using "xcodebuild -workspace gutenberg.xcworkspace -configuration Debug -scheme gutenberg -destination id=860DC2DE-1126-4395-98E2-B5A89E804633 -derivedDataPath build/gutenberg")
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
info Installing "DerivedData/Build/Products/Debug-iphonesimulator/gutenberg.app"
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
error Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/gutenberg.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
. Run CLI with --verbose flag for more details.
Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier DerivedData/Build/Products/Debug-iphonesimulator/gutenberg.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at runOnSimulator (/Users/stefanos/proj/a8c/rn/t1/gutenberg-mobile/gutenberg/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:183:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/stefanos/proj/a8c/rn/t1/gutenberg-mobile/gutenberg/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:182:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @wordpress/react-native-editor@1.37.0 ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @wordpress/react-native-editor@1.37.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefanos/.npm/_logs/2020-09-21T10_53_26_741Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@9.0.0 native: `npm run --prefix packages/react-native-editor "ios"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gutenberg@9.0.0 native script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefanos/.npm/_logs/2020-09-21T10_53_26_781Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg-mobile@1.36.0 core: `cd gutenberg && npm run native "ios"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gutenberg-mobile@1.36.0 core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefanos/.npm/_logs/2020-09-21T10_53_26_808Z-debug.log
```
5. Error doesn't happen if you open the demo project on Xcode directly and build+run from there

On macos 10.15.6, Xcode v12.0

**Comment by guarani** [comment]
FWIW the current workaround is to run `bundle exec pod install` in the `packages/react-native-editor/ios` folder, then open the project (`packages/react-native-editor/ios/gutenberg.xcworkspace`) from Xcode 12, and run it from there.
