### ISSUE TITLE
Android react-native-gutenberg-bridge Bintray upload fails to build due to npx

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/gutenberg-mobile#2972]
As you can see from #2945, when attempting to build the AAR to publish to Bintray, via the `assembleRelease` task, we get a failure due to `npx` failing under the hood.

As far as I can tell, the sub task that's failing is `app:bundleReleaseJsAndAssets`. I've run the build twice. The [first time](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/9720/workflows/3688f362-78bf-4804-ad60-88762a30f6d3/jobs/51519) I got

```
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx'' finished with non-zero exit value 137
```

That exit code _might_ have to do with the CI machine running out of memory, even though that seems bizarre, see [this issue on `npm`](https://github.com/npm/npm/issues/4008).

The [second time](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/9720/workflows/2de2ad87-8b07-4ecd-8b5b-85a03da2f313/jobs/51984), I got 

```
Error: Cannot find module '@babel/parser'
...
> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx'' finished with non-zero exit value 1
```

**Comment by mokagio** [comment]
As far as I understand from [this comment in the code](https://github.com/WordPress/gutenberg/blob/62e074b3d6a57e06d017a94c1d38c1cef16b2e93/packages/react-native-editor/android/app/build.gradle#L6-L9), `bundleReleaseJsAndAssets` is something that the React Native build systems adds.

**Comment by mokagio** [comment]
cc @oguzkocer

**Comment by mokagio** [comment]
I added a `--debug` flag to `./gradlew assembleRelease` and the extra information to points indeed to an out of memory error:

```
05:34:46.837 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :app:bundleReleaseJsAndAssets
05:36:01.262 [QUIET] [system.out] Error: ENOMEM: not enough memory, read
05:36:01.272 [QUIET] [system.out]     at Object.readSync (fs.js:568:3)
05:36:01.272 [QUIET] [system.out]     at tryReadSync (fs.js:353:20)
05:36:01.272 [QUIET] [system.out]     at Object.readFileSync (fs.js:382:19)
05:36:01.272 [QUIET] [system.out]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1034:22)
05:36:01.272 [QUIET] [system.out]     at Module.load (internal/modules/cjs/loader.js:879:32)
05:36:01.272 [QUIET] [system.out]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
05:36:01.272 [QUIET] [system.out]     at Module.require (internal/modules/cjs/loader.js:903:19)
05:36:01.272 [QUIET] [system.out]     at require (internal/modules/cjs/helpers.js:74:18)
05:36:01.266 [ERROR] [system.err] error ../../node_modules/react-native/Libraries/Animated/src/AnimatedEvent.js: ENOMEM: not enough memory, read. Run CLI with --verbose flag for more details.
05:36:01.274 [QUIET] [system.out]     at Object.<anonymous> (/home/circleci/project/gutenberg/node_modules/metro-react-native-babel-preset/src/configs/main.js:72:4)
```

Full build on CircleCI [here](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/9814/workflows/bb85c901-a739-4edb-8d5a-b2078cfdb5cc/jobs/51992).

Now... 🤔 Why is it running out of memory? What can I tweak in the setup? Why isn't it happening in other tasks?

**Comment by oguzkocer** [comment]
@mokagio It looks like we don't have a `gradle.properties` file being copied for this task, I assume it was never setup for this repo. This doesn't seem like a typical Gradle memory error but rather one on the React native side, so maybe it's unrelated. However, copying the `gradle.properties` is fairly easy, so I'd give that a try.

For WPAndroid, we do the `gradle.properties` copy [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/.circleci/config.yml#L20-L24) and the memory relevant bit should be [this one](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/gradle.properties-example#L5).

Also, you can ssh into the VM and run the task manually to test things faster.

Hope this helps!
