### ISSUE TITLE
[Android] NativeViewHierarchyManager: Unable to update properties for view tag 693

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#312]
Previously reported in a comment here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/311 I thought to open a separate issue for this Error.

```
2018-12-03 14:23:01.877 13822-13822/com.gutenberg E/unknown:NativeViewHierarchyManager: Unable to update properties for view tag 495
    com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 495 could not be found
        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:107)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:134)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:338)
        at com.facebook.react.animated.PropsAnimatedNode.restoreDefaultValues(PropsAnimatedNode.java:76)
        at com.facebook.react.animated.NativeAnimatedNodesManager.restoreDefaultValues(NativeAnimatedNodesManager.java:337)
        at com.facebook.react.animated.NativeAnimatedModule$18.execute(NativeAnimatedModule.java:350)
        at com.facebook.react.animated.NativeAnimatedModule$2.execute(NativeAnimatedModule.java:141)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:567)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:894)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Steps to reproduce:
- Start the demo app
- Select a RichText block 
- Move it down to the bottom of the list
- Go at the top and select the first block
- Move some blocks up/down (This is not always required, but putting it here to make the issue happen faster)
- Go back to bottom and tap into the RichText block

It seems that could be related to the `TouchableWithoutFeedback` element that is wrapping our AztecView here: https://github.com/wordpress-mobile/react-native-aztec/blob/master/src/AztecView.js#L134

When I removed the `TouchableWithoutFeedback` the error was hard to reproduce.

**Comment by daniloercoli** [comment]
Cannot reproduce after https://github.com/wordpress-mobile/gutenberg-mobile/pull/314 has been merged.
