### ISSUE TITLE
[WPAndroid] Missing images

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/gutenberg-mobile#422]
1. Open the App
1. Click on the Add New Post
2. Click on the + icon in the 'toolbar'
3. Click on "Image"
4. Click on "Media Library"
5. Select an image
6. Click on the "check" icon in the top right corner
7. The image block is there -> but the image is missing
![screenshot_1545327254](https://user-images.githubusercontent.com/2261188/50300830-e6bfc600-0485-11e9-875a-fa303b6a7a7e.png)

It even crashed once when I clicked on the image -> I'm not sure if it's related.
```
2018-12-20 18:28:38.045 19841-20007/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: org.wordpress.android, PID: 19841
    com.facebook.react.uimanager.IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand on view with tag: 117, since the view does not exists
        at com.facebook.react.uimanager.UIImplementation.assertViewExists(UIImplementation.java:919)
        at com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand(UIImplementation.java:798)
        at com.facebook.react.uimanager.UIManagerModule.dispatchCommand(UIManagerModule.java:637)
        at com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand(UIManagerModule.java:632)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

Emulator Pixel 2 - API 27

**Comment by malinajirka** [comment]
I haven't realized the site was private -> duplicate https://github.com/wordpress-mobile/gutenberg-mobile/issues/376
